const prisma = require('../models/index');
const providerData = require('./seedProvider');
// sample data here

const userData = [
  {
    userId: 'U12345BKK',
    firstName: 'Alice',
    lastName: 'Wang',
    email: 'alice.wang@example.com',
    phoneNumber: '+66 123 456 789',
  },
  {
    userId: 'U23456BKK',
    firstName: 'Ben',
    lastName: 'Tan',
    email: 'ben.tan@example.com',
    phoneNumber: '+66 234 567 890',
  },
  {
    userId: 'U34567BKK',
    firstName: 'Chloe',
    lastName: 'Liu',
    email: 'chloe.liu@example.com',
    phoneNumber: '+66 345 678 901',
  },
  {
    userId: 'U45678BKK',
    firstName: 'Daniel',
    lastName: 'Smith',
    email: 'daniel.smith@example.com',
    phoneNumber: '+66 456 789 012',
  },
  {
    userId: 'U56789BKK',
    firstName: 'Eva',
    lastName: 'Nguyen',
    email: 'eva.nguyen@example.com',
    phoneNumber: '+66 567 890 123',
  },
  {
    userId: 'U67890BKK',
    firstName: 'Felix',
    lastName: 'Chavez',
    email: 'felix.chavez@example.com',
    phoneNumber: '+66 678 901 234',
  },
  {
    userId: 'U78901BKK',
    firstName: 'Grace',
    lastName: 'Kim',
    email: 'grace.kim@example.com',
    phoneNumber: '+66 789 012 345',
  },
  {
    userId: 'U89012BKK',
    firstName: 'Henry',
    lastName: 'Martinez',
    email: 'henry.martinez@example.com',
    phoneNumber: '+66 890 123 456',
  },
  {
    userId: 'U90123BKK',
    firstName: 'Ivy',
    lastName: 'Lee',
    email: 'ivy.lee@example.com',
    phoneNumber: '+66 901 234 567',
  },
  {
    userId: 'U01234BKK',
    firstName: 'Jack',
    lastName: 'Johnson',
    email: 'jack.johnson@example.com',
    phoneNumber: '+66 012 345 678',
  },
  {
    userId: 'U13579BKK',
    firstName: 'Kara',
    lastName: 'Davis',
    email: 'kara.davis@example.com',
    phoneNumber: '+66 123 678 901',
  },
  {
    userId: 'U24680BKK',
    firstName: 'Leo',
    lastName: 'Zhang',
    email: 'leo.zhang@example.com',
    phoneNumber: '+66 234 789 012',
  },
  {
    userId: 'U35791BKK',
    firstName: 'Maya',
    lastName: 'Chen',
    email: 'maya.chen@example.com',
    phoneNumber: '+66 345 890 123',
  },
  {
    userId: 'U46802BKK',
    firstName: 'Nathan',
    lastName: 'Lee',
    email: 'nathan.lee@example.com',
    phoneNumber: '+66 456 901 234',
  },
  {
    userId: 'U57913BKK',
    firstName: 'Olivia',
    lastName: 'Taylor',
    email: 'olivia.taylor@example.com',
    phoneNumber: '+66 567 012 345',
  },
  {
    userId: 'U68024BKK',
    firstName: 'Peter',
    lastName: 'Wilson',
    email: 'peter.wilson@example.com',
    phoneNumber: '+66 678 123 456',
  },
  {
    userId: 'U79135BKK',
    firstName: 'Quinn',
    lastName: 'Lopez',
    email: 'quinn.lopez@example.com',
    phoneNumber: '+66 789 234 567',
  },
  {
    userId: 'U80246BKK',
    firstName: 'Riley',
    lastName: 'Morris',
    email: 'riley.morris@example.com',
    phoneNumber: '+66 890 345 678',
  },
  {
    userId: 'U91357BKK',
    firstName: 'Sophia',
    lastName: 'Garcia',
    email: 'sophia.garcia@example.com',
    phoneNumber: '+66 901 456 789',
  },
  {
    userId: 'U02468BKK',
    firstName: 'Tom',
    lastName: 'Hernandez',
    email: 'tom.hernandez@example.com',
    phoneNumber: '+66 012 567 890',
  },
];

const categoryData = [
  {
    categoryId: 1,
    categoryName: 'Caring',
    categoryIcon: 'Icon1',
    subCatId: 11,
    subCatName: 'Child Care',
  },
  {
    categoryId: 1,
    categoryName: 'Caring',
    categoryIcon: 'Icon1',
    subCatId: 12,
    subCatName: 'Elderly Care',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 21,
    subCatName: 'General Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 22,
    subCatName: 'A/C Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 23,
    subCatName: 'Car Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 24,
    subCatName: 'Washing Machine Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 25,
    subCatName: 'Water Tank Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 26,
    subCatName: 'Niche Cleaning',
  },
  {
    categoryId: 3,
    categoryName: 'Laundry',
    categoryIcon: 'Icon3',
    subCatId: 31,
    subCatName: 'General Laundry',
  },
  {
    categoryId: 3,
    categoryName: 'Laundry',
    categoryIcon: 'Icon3',
    subCatId: 32,
    subCatName: 'Bedding Laundry',
  },
  {
    categoryId: 4,
    categoryName: 'Transport',
    categoryIcon: 'Icon4',
    subCatId: 41,
    subCatName: 'General Transport',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 51,
    subCatName: 'Plumbing',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 52,
    subCatName: 'Electrician',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 53,
    subCatName: 'HVAC',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 54,
    subCatName: 'Construction',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 55,
    subCatName: 'Painting',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 56,
    subCatName: 'Woodwork',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 57,
    subCatName: 'Roofing',
  },
  {
    categoryId: 6,
    categoryName: 'Pet Care',
    categoryIcon: 'Icon6',
    subCatId: 61,
    subCatName: 'Pet Boarding',
  },
  {
    categoryId: 6,
    categoryName: 'Pet Care',
    categoryIcon: 'Icon6',
    subCatId: 62,
    subCatName: 'Pet Grooming',
  },
  {
    categoryId: 7,
    categoryName: 'Gardening',
    categoryIcon: 'Icon7',
    subCatId: 71,
    subCatName: 'Tree Services',
  },
  {
    categoryId: 7,
    categoryName: 'Gardening',
    categoryIcon: 'Icon7',
    subCatId: 72,
    subCatName: 'General Gardening',
  },
];

const serviceData = [
  {
    providerId: 'P10000BKK',
    subCatId: 11,
  },
  {
    providerId: 'P10001BKK',
    subCatId: 12,
  },
  {
    providerId: 'P10002BKK',
    subCatId: 21,
  },
  {
    providerId: 'P10003BKK',
    subCatId: 22,
  },
  {
    providerId: 'P10004BKK',
    subCatId: 23,
  },
  {
    providerId: 'P10005BKK',
    subCatId: 24,
  },
  {
    providerId: 'P10006BKK',
    subCatId: 31,
  },
  {
    providerId: 'P10007BKK',
    subCatId: 32,
  },
];

// const providerData = [
//   {
//     providerId: 'P10000BKK',
//     firstName: 'Ariya',
//     lastName: 'Srisuk',
//     email: 'ariya.srisuk@example.com',
//     phoneNumber: '+66 123 456 789',
//     latitude: 13.7563,
//     longitude: 100.5018,
//     address: '12/3 Sukhumvit Road, Bangkok',
//     skills: 3,
//   },
//   {
//     providerId: 'P10001BKK',
//     firstName: 'Chai',
//     lastName: 'Wongsa',
//     email: 'chai.wongsa@example.com',
//     phoneNumber: '+66 987 654 321',
//     latitude: 13.7365,
//     longitude: 100.5238,
//     address: '45/6 Silom Road, Bangkok',
//     skills: 1,
//   },
//   {
//     providerId: 'P10002BKK',
//     firstName: 'Dao',
//     lastName: 'Pimjai',
//     email: 'dao.pimjai@example.com',
//     phoneNumber: '+66 555 123 456',
//     latitude: 13.789,
//     longitude: 100.5432,
//     address: '78/9 Rama I Road, Bangkok',
//     skills: 5,
//   },
//   {
//     providerId: 'P10003BKK',
//     firstName: 'Ekachai',
//     lastName: 'Rattana',
//     email: 'ekachai.rattana@example.com',
//     phoneNumber: '+66 111 222 333',
//     latitude: 13.7654,
//     longitude: 100.5123,
//     address: '10/11 Phetchaburi Road, Bangkok',
//     skills: 7,
//   },
//   {
//     providerId: 'P10004BKK',
//     firstName: 'Fah',
//     lastName: 'Srisawat',
//     email: 'fah.srisawat@example.com',
//     phoneNumber: '+66 444 555 666',
//     latitude: 13.7432,
//     longitude: 100.5345,
//     address: '13/14 Charoen Krung Road, Bangkok',
//     skills: 2,
//   },
//   {
//     providerId: 'P10005BKK',
//     firstName: 'Garn',
//     lastName: 'Thongdee',
//     email: 'garn.thongdee@example.com',
//     phoneNumber: '+66 777 888 999',
//     latitude: 13.7789,
//     longitude: 100.521,
//     address: '16/17 Lat Phrao Road, Bangkok',
//     skills: 4,
//   },
//   {
//     providerId: 'P10006BKK',
//     firstName: 'Hong',
//     lastName: 'Chaiyo',
//     email: 'hong.chaiyo@example.com',
//     phoneNumber: '+66 222 333 444',
//     latitude: 13.7543,
//     longitude: 100.5098,
//     address: '19/20 Rama IV Road, Bangkok',
//     skills: 6,
//   },
//   {
//     providerId: 'P10007BKK',
//     firstName: 'Ing',
//     lastName: 'Sookjai',
//     email: 'ing.sookjai@example.com',
//     phoneNumber: '+66 666 777 888',
//     latitude: 13.7321,
//     longitude: 100.5456,
//     address: '22/23 Ratchadaphisek Road, Bangkok',
//     skills: 1,
//   },
//   {
//     providerId: 'P10008BKK',
//     firstName: 'Jit',
//     lastName: 'Panya',
//     email: 'jit.panya@example.com',
//     phoneNumber: '+66 888 999 000',
//     latitude: 13.7901,
//     longitude: 100.5321,
//     address: '25/26 Phaya Thai Road, Bangkok',
//     skills: 3,
//   },
//   {
//     providerId: 'P10009BKK',
//     firstName: 'Kamon',
//     lastName: 'Decha',
//     email: 'kamon.decha@example.com',
//     phoneNumber: '+66 333 444 555',
//     latitude: 13.7678,
//     longitude: 100.5109,
//     address: '28/29 Vibhavadi Rangsit Road, Bangkok',
//     skills: 5,
//   },
//   {
//     providerId: 'P10099BKK',
//     firstName: 'Ying',
//     lastName: 'Raksasri',
//     email: 'ying.raksasri@example.com',
//     phoneNumber: '+66 999 888 777',
//     latitude: 13.7444,
//     longitude: 100.5555,
//     address: '99/100 Din Daeng Road, Bangkok',
//     skills: 7,
//   },
//   {
//     providerId: 'P10100BKK',
//     firstName: 'Kriangkrai',
//     lastName: 'Chaiyot',
//     email: 'kriangkrai.chaiyot@example.com',
//     phoneNumber: '+66 101 202 303',
//     latitude: 13.77,
//     longitude: 100.49,
//     address: '101/102 Ratchadamnoen Avenue, Bangkok',
//     skills: 2,
//   },
//   {
//     providerId: 'P10101BKK',
//     firstName: 'Lalita',
//     lastName: 'Wongsin',
//     email: 'lalita.wongsin@example.com',
//     phoneNumber: '+66 202 303 404',
//     latitude: 13.74,
//     longitude: 100.53,
//     address: '103/104 Phahonyothin Road, Bangkok',
//     skills: 6,
//   },
//   {
//     providerId: 'P10102BKK',
//     firstName: 'Mana',
//     lastName: 'Sombat',
//     email: 'mana.sombat@example.com',
//     phoneNumber: '+66 303 404 505',
//     latitude: 13.78,
//     longitude: 100.51,
//     address: '105/106 Thanon Krung Kasem, Bangkok',
//     skills: 4,
//   },
//   {
//     providerId: 'P10103BKK',
//     firstName: 'Narumol',
//     lastName: 'Kittipong',
//     email: 'narumol.kittipong@example.com',
//     phoneNumber: '+66 404 505 606',
//     latitude: 13.76,
//     longitude: 100.54,
//     address: '107/108 Yaowarat Road, Bangkok',
//     skills: 1,
//   },
//   {
//     providerId: 'P10104BKK',
//     firstName: 'Olan',
//     lastName: 'Chuchuay',
//     email: 'olan.chuchuay@example.com',
//     phoneNumber: '+66 505 606 707',
//     latitude: 13.73,
//     longitude: 100.5,
//     address: '109/110 Ratchadamri Road, Bangkok',
//     skills: 3,
//   },
//   {
//     providerId: 'P10105BKK',
//     firstName: 'Pajaree',
//     lastName: 'Srisuwan',
//     email: 'pajaree.srisuwan@example.com',
//     phoneNumber: '+66 606 707 808',
//     latitude: 13.79,
//     longitude: 100.52,
//     address: '111/112 Charoen Nakhon Road, Bangkok',
//     skills: 7,
//   },
//   {
//     providerId: 'P10106BKK',
//     firstName: 'Qasim',
//     lastName: 'Abbas',
//     email: 'qasim.abbas@example.com',
//     phoneNumber: '+66 707 808 909',
//     latitude: 13.75,
//     longitude: 100.55,
//     address: '113/114 Rama V Road, Bangkok',
//     skills: 5,
//   },
//   {
//     providerId: 'P10107BKK',
//     firstName: 'Rachanee',
//     lastName: 'Pornchai',
//     email: 'rachanee.pornchai@example.com',
//     phoneNumber: '+66 808 909 010',
//     latitude: 13.72,
//     longitude: 100.48,
//     address: '115/116 Thanon Sukhumvit 71, Bangkok',
//     skills: 1,
//   },
//   {
//     providerId: 'P10108BKK',
//     firstName: 'Somsak',
//     lastName: 'Jaidee',
//     email: 'somsak.jaidee@example.com',
//     phoneNumber: '+66 909 010 111',
//     latitude: 13.785,
//     longitude: 100.535,
//     address: '117/118 Soi Cowboy, Bangkok',
//     skills: 3,
//   },
//   {
//     providerId: 'P10109BKK',
//     firstName: 'Tanaporn',
//     lastName: 'Kanjanapong',
//     email: 'tanaporn.kanjanapong@example.com',
//     phoneNumber: '+66 010 111 212',
//     latitude: 13.745,
//     longitude: 100.515,
//     address: '119/120 Silom Soi 4, Bangkok',
//     skills: 7,
//   },
//   {
//     providerId: 'P10110BKK',
//     firstName: 'Udom',
//     lastName: 'Srisuwan',
//     email: 'udom.srisuwan@example.com',
//     phoneNumber: '+66 111 212 313',
//     latitude: 13.765,
//     longitude: 100.525,
//     address: '121/122 Thanon Asok Montri, Bangkok',
//     skills: 4,
//   },
//   {
//     providerId: 'P10111BKK',
//     firstName: 'Vichai',
//     lastName: 'Wongyai',
//     email: 'vichai.wongyai@example.com',
//     phoneNumber: '+66 212 313 414',
//     latitude: 13.735,
//     longitude: 100.505,
//     address: '123/124 Thanon Ratchadamnoen Klang, Bangkok',
//     skills: 1,
//   },
//   {
//     providerId: 'P10112BKK',
//     firstName: 'Wanna',
//     lastName: 'Petchsuk',
//     email: 'wanna.petchsuk@example.com',
//     phoneNumber: '+66 313 414 515',
//     latitude: 13.795,
//     longitude: 100.545,
//     address: '125/126 Thanon Phaya Thai, Bangkok',
//     skills: 7,
//   },
//   {
//     providerId: 'P10113BKK',
//     firstName: 'Xavier',
//     lastName: 'Rodriguez',
//     email: 'xavier.rodriguez@example.com',
//     phoneNumber: '+66 414 515 616',
//     latitude: 13.755,
//     longitude: 100.495,
//     address: '127/128 Thanon Rama IX, Bangkok',
//     skills: 2,
//   },
//   {
//     providerId: 'P10114BKK',
//     firstName: 'Yaowalak',
//     lastName: 'Chaisong',
//     email: 'yaowalak.chaisong@example.com',
//     phoneNumber: '+66 515 616 717',
//     latitude: 13.725,
//     longitude: 100.535,
//     address: '129/130 Thanon Charoen Krung, Bangkok',
//     skills: 5,
//   },
//   {
//     providerId: 'P10115BKK',
//     firstName: 'Zackary',
//     lastName: 'Smith',
//     email: 'zackary.smith@example.com',
//     phoneNumber: '+66 616 717 818',
//     latitude: 13.785,
//     longitude: 100.515,
//     address: '131/132 Thanon Vibhavadi Rangsit, Bangkok',
//     skills: 3,
//   },
//   {
//     providerId: 'P10116BKK',
//     firstName: 'Anong',
//     lastName: 'Sookdee',
//     email: 'anong.sookdee@example.com',
//     phoneNumber: '+66 717 818 919',
//     latitude: 13.745,
//     longitude: 100.555,
//     address: '133/134 Thanon Lat Phrao, Bangkok',
//     skills: 1,
//   },
//   {
//     providerId: 'P10117BKK',
//     firstName: 'Boonmee',
//     lastName: 'Deesuk',
//     email: 'boonmee.deesuk@example.com',
//     phoneNumber: '+66 818 919 020',
//     latitude: 13.715,
//     longitude: 100.485,
//     address: '135/136 Thanon Rama IV, Bangkok',
//     skills: 6,
//   },
//   {
//     providerId: 'P10118BKK',
//     firstName: 'Chalerm',
//     lastName: 'Rattanachai',
//     email: 'chalerm.rattanachai@example.com',
//     phoneNumber: '+66 919 020 121',
//     latitude: 13.775,
//     longitude: 100.535,
//     address: '137/138 Thanon Ratchadaphisek, Bangkok',
//     skills: 4,
//   },
//   {
//     providerId: 'P10119BKK',
//     firstName: 'Daranee',
//     lastName: 'Panyawut',
//     email: 'daranee.panyawut@example.com',
//     phoneNumber: '+66 020 121 222',
//     latitude: 13.735,
//     longitude: 100.505,
//     address: '139/140 Thanon Phaya Thai, Bangkok',
//     skills: 2,
//   },
//   {
//     providerId: 'P10120BKK',
//     firstName: 'Ekarin',
//     lastName: 'Wongthep',
//     email: 'ekarin.wongthep@example.com',
//     phoneNumber: '+66 121 222 323',
//     latitude: 13.795,
//     longitude: 100.545,
//     address: '141/142 Thanon Sukhumvit, Bangkok',
//     skills: 7,
//   },
//   {
//     providerId: 'P10121BKK',
//     firstName: 'Fonthip',
//     lastName: 'Kittisak',
//     email: 'fonthip.kittisak@example.com',
//     phoneNumber: '+66 222 323 424',
//     latitude: 13.755,
//     longitude: 100.495,
//     address: '143/144 Thanon Silom, Bangkok',
//     skills: 5,
//   },
//   {
//     providerId: 'P10122BKK',
//     firstName: 'Gumpanart',
//     lastName: 'Chaisiri',
//     email: 'gumpanart.chaisiri@example.com',
//     phoneNumber: '+66 323 424 525',
//     latitude: 13.725,
//     longitude: 100.535,
//     address: '145/146 Thanon Rama I, Bangkok',
//     skills: 3,
//   },
//   {
//     providerId: 'P10123BKK',
//     firstName: 'Hathairat',
//     lastName: 'Srisombat',
//     email: 'hathairat.srisombat@example.com',
//     phoneNumber: '+66 424 525 626',
//     latitude: 13.785,
//     longitude: 100.515,
//     address: '147/148 Thanon Phetchaburi, Bangkok',
//     skills: 1,
//   },
//   {
//     providerId: 'P10124BKK',
//     firstName: 'Isariya',
//     lastName: 'Thongbai',
//     email: 'isariya.thongbai@example.com',
//     phoneNumber: '+66 525 626 727',
//     latitude: 13.745,
//     longitude: 100.555,
//     address: '149/150 Thanon Charoen Krung, Bangkok',
//     skills: 6,
//   },
//   {
//     providerId: 'P10125BKK',
//     firstName: 'Jirayu',
//     lastName: 'Dechatiwong',
//     email: 'jirayu.dechatiwong@example.com',
//     phoneNumber: '+66 626 727 828',
//     latitude: 13.715,
//     longitude: 100.485,
//     address: '151/152 Thanon Rama IV, Bangkok',
//     skills: 4,
//   },
//   {
//     providerId: 'P10126BKK',
//     firstName: 'Kanchana',
//     lastName: 'Raksasri',
//     email: 'kanchana.raksasri@example.com',
//     phoneNumber: '+66 727 828 929',
//     latitude: 13.775,
//     longitude: 100.535,
//     address: '153/154 Thanon Ratchadaphisek, Bangkok',
//     skills: 2,
//   },
//   {
//     providerId: 'P10127BKK',
//     firstName: 'Lerdchai',
//     lastName: 'Jaidee',
//     email: 'lerdchai.jaidee@example.com',
//     phoneNumber: '+66 828 929 030',
//     latitude: 13.735,
//     longitude: 100.505,
//     address: '155/156 Thanon Phaya Thai, Bangkok',
//     skills: 7,
//   },
//   {
//     providerId: 'P10128BKK',
//     firstName: 'Malee',
//     lastName: 'Sombat',
//     email: 'malee.sombat@example.com',
//     phoneNumber: '+66 929 030 131',
//     latitude: 13.795,
//     longitude: 100.545,
//     address: '157/158 Thanon Sukhumvit, Bangkok',
//     skills: 5,
//   },
//   {
//     providerId: 'P10129BKK',
//     firstName: 'Nattapong',
//     lastName: 'Kittipong',
//     email: 'nattapong.kittipong@example.com',
//     phoneNumber: '+66 030 131 232',
//     latitude: 13.755,
//     longitude: 100.495,
//     address: '159/160 Thanon Silom, Bangkok',
//     skills: 3,
//   },
// ];

async function seedDatabase() {
  // prisma command here

  await prisma.user.createMany({
    data: userData,
  });

  await prisma.provider.createMany({
    data: providerData.providerData,
  });

  await prisma.category.createMany({
    data: categoryData,
  });

  await prisma.service.createMany({
    data: serviceData,
  });
}

console.log('Seeding Database...');
seedDatabase();
