const prisma = require('../models/index');

// sample data here

const userData = [
  {
    userId: 'U12345BKK',
    firstName: 'Alice',
    lastName: 'Wang',
    email: 'alice.wang@example.com',
    phoneNumber: '+66 123 456 789',
  },
  {
    userId: 'U23456BKK',
    firstName: 'Ben',
    lastName: 'Tan',
    email: 'ben.tan@example.com',
    phoneNumber: '+66 234 567 890',
  },
  {
    userId: 'U34567BKK',
    firstName: 'Chloe',
    lastName: 'Liu',
    email: 'chloe.liu@example.com',
    phoneNumber: '+66 345 678 901',
  },
  {
    userId: 'U45678BKK',
    firstName: 'Daniel',
    lastName: 'Smith',
    email: 'daniel.smith@example.com',
    phoneNumber: '+66 456 789 012',
  },
  {
    userId: 'U56789BKK',
    firstName: 'Eva',
    lastName: 'Nguyen',
    email: 'eva.nguyen@example.com',
    phoneNumber: '+66 567 890 123',
  },
  {
    userId: 'U67890BKK',
    firstName: 'Felix',
    lastName: 'Chavez',
    email: 'felix.chavez@example.com',
    phoneNumber: '+66 678 901 234',
  },
  {
    userId: 'U78901BKK',
    firstName: 'Grace',
    lastName: 'Kim',
    email: 'grace.kim@example.com',
    phoneNumber: '+66 789 012 345',
  },
  {
    userId: 'U89012BKK',
    firstName: 'Henry',
    lastName: 'Martinez',
    email: 'henry.martinez@example.com',
    phoneNumber: '+66 890 123 456',
  },
  {
    userId: 'U90123BKK',
    firstName: 'Ivy',
    lastName: 'Lee',
    email: 'ivy.lee@example.com',
    phoneNumber: '+66 901 234 567',
  },
  {
    userId: 'U01234BKK',
    firstName: 'Jack',
    lastName: 'Johnson',
    email: 'jack.johnson@example.com',
    phoneNumber: '+66 012 345 678',
  },
  {
    userId: 'U13579BKK',
    firstName: 'Kara',
    lastName: 'Davis',
    email: 'kara.davis@example.com',
    phoneNumber: '+66 123 678 901',
  },
  {
    userId: 'U24680BKK',
    firstName: 'Leo',
    lastName: 'Zhang',
    email: 'leo.zhang@example.com',
    phoneNumber: '+66 234 789 012',
  },
  {
    userId: 'U35791BKK',
    firstName: 'Maya',
    lastName: 'Chen',
    email: 'maya.chen@example.com',
    phoneNumber: '+66 345 890 123',
  },
  {
    userId: 'U46802BKK',
    firstName: 'Nathan',
    lastName: 'Lee',
    email: 'nathan.lee@example.com',
    phoneNumber: '+66 456 901 234',
  },
  {
    userId: 'U57913BKK',
    firstName: 'Olivia',
    lastName: 'Taylor',
    email: 'olivia.taylor@example.com',
    phoneNumber: '+66 567 012 345',
  },
  {
    userId: 'U68024BKK',
    firstName: 'Peter',
    lastName: 'Wilson',
    email: 'peter.wilson@example.com',
    phoneNumber: '+66 678 123 456',
  },
  {
    userId: 'U79135BKK',
    firstName: 'Quinn',
    lastName: 'Lopez',
    email: 'quinn.lopez@example.com',
    phoneNumber: '+66 789 234 567',
  },
  {
    userId: 'U80246BKK',
    firstName: 'Riley',
    lastName: 'Morris',
    email: 'riley.morris@example.com',
    phoneNumber: '+66 890 345 678',
  },
  {
    userId: 'U91357BKK',
    firstName: 'Sophia',
    lastName: 'Garcia',
    email: 'sophia.garcia@example.com',
    phoneNumber: '+66 901 456 789',
  },
  {
    userId: 'U02468BKK',
    firstName: 'Tom',
    lastName: 'Hernandez',
    email: 'tom.hernandez@example.com',
    phoneNumber: '+66 012 567 890',
  },
];

const categoryData = [
  {
    categoryId: 1,
    categoryName: 'Caring',
    categoryIcon: 'Icon1',
    subCatId: 11,
    subCatName: 'Child Care',
  },
  {
    categoryId: 1,
    categoryName: 'Caring',
    categoryIcon: 'Icon1',
    subCatId: 12,
    subCatName: 'Elderly Care',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 21,
    subCatName: 'General Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 22,
    subCatName: 'A/C Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 23,
    subCatName: 'Car Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 24,
    subCatName: 'Washing Machine Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 25,
    subCatName: 'Water Tank Cleaning',
  },
  {
    categoryId: 2,
    categoryName: 'Cleaning',
    categoryIcon: 'Icon2',
    subCatId: 26,
    subCatName: 'Niche Cleaning',
  },
  {
    categoryId: 3,
    categoryName: 'Laundry',
    categoryIcon: 'Icon3',
    subCatId: 31,
    subCatName: 'General Laundry',
  },
  {
    categoryId: 3,
    categoryName: 'Laundry',
    categoryIcon: 'Icon3',
    subCatId: 32,
    subCatName: 'Bedding Laundry',
  },
  {
    categoryId: 4,
    categoryName: 'Transport',
    categoryIcon: 'Icon4',
    subCatId: 41,
    subCatName: 'General Transport',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 51,
    subCatName: 'Plumbing',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 52,
    subCatName: 'Electrician',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 53,
    subCatName: 'HVAC',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 54,
    subCatName: 'Construction',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 55,
    subCatName: 'Painting',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 56,
    subCatName: 'Woodwork',
  },
  {
    categoryId: 5,
    categoryName: 'Repair',
    categoryIcon: 'Icon5',
    subCatId: 57,
    subCatName: 'Roofing',
  },
  {
    categoryId: 6,
    categoryName: 'Pet Care',
    categoryIcon: 'Icon6',
    subCatId: 61,
    subCatName: 'Pet Boarding',
  },
  {
    categoryId: 6,
    categoryName: 'Pet Care',
    categoryIcon: 'Icon6',
    subCatId: 62,
    subCatName: 'Pet Grooming',
  },
  {
    categoryId: 7,
    categoryName: 'Gardening',
    categoryIcon: 'Icon7',
    subCatId: 71,
    subCatName: 'Tree Services',
  },
  {
    categoryId: 7,
    categoryName: 'Gardening',
    categoryIcon: 'Icon7',
    subCatId: 72,
    subCatName: 'General Gardening',
  },
];

const providerData = [
  {
    providerId: 'P12345BKK',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phoneNumber: '+66 123 456 789',
    latitude: 13.7563,
    longitude: 100.5018,
  },
  {
    providerId: 'P54321BKK',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    phoneNumber: '+66 234 567 890',
    latitude: 13.75,
    longitude: 100.5167,
  },
  {
    providerId: 'P23456BKK',
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael.johnson@example.com',
    phoneNumber: '+66 345 678 901',
    latitude: 13.7567,
    longitude: 100.5166,
  },
  {
    providerId: 'P87654BKK',
    firstName: 'Emily',
    lastName: 'Taylor',
    email: 'emily.taylor@example.com',
    phoneNumber: '+66 456 789 012',
    latitude: 13.753,
    longitude: 100.5025,
  },
  {
    providerId: 'P65432BKK',
    firstName: 'David',
    lastName: 'Martinez',
    email: 'david.martinez@example.com',
    phoneNumber: '+66 567 890 123',
    latitude: 13.7509,
    longitude: 100.5083,
  },
  {
    providerId: 'P11223BKK',
    firstName: 'Laura',
    lastName: 'Davis',
    email: 'laura.davis@example.com',
    phoneNumber: '+66 678 901 234',
    latitude: 13.7595,
    longitude: 100.5158,
  },
  {
    providerId: 'P22334BKK',
    firstName: 'Daniel',
    lastName: 'Garcia',
    email: 'daniel.garcia@example.com',
    phoneNumber: '+66 789 012 345',
    latitude: 13.7589,
    longitude: 100.5033,
  },
  {
    providerId: 'P33445BKK',
    firstName: 'Sophia',
    lastName: 'Lee',
    email: 'sophia.lee@example.com',
    phoneNumber: '+66 890 123 456',
    latitude: 13.7537,
    longitude: 100.507,
  },
  {
    providerId: 'P44556BKK',
    firstName: 'James',
    lastName: 'Miller',
    email: 'james.miller@example.com',
    phoneNumber: '+66 901 234 567',
    latitude: 13.7572,
    longitude: 100.5112,
  },
  {
    providerId: 'P55667BKK',
    firstName: 'Olivia',
    lastName: 'Wilson',
    email: 'olivia.wilson@example.com',
    phoneNumber: '+66 012 345 678',
    latitude: 13.7543,
    longitude: 100.5095,
  },
  {
    providerId: 'P66778BKK',
    firstName: 'Benjamin',
    lastName: 'Moore',
    email: 'benjamin.moore@example.com',
    phoneNumber: '+66 123 789 456',
    latitude: 13.759,
    longitude: 100.5087,
  },
  {
    providerId: 'P77889BKK',
    firstName: 'Mia',
    lastName: 'Clark',
    email: 'mia.clark@example.com',
    phoneNumber: '+66 234 890 567',
    latitude: 13.7561,
    longitude: 100.5074,
  },
  {
    providerId: 'P88990BKK',
    firstName: 'Ethan',
    lastName: 'Rodriguez',
    email: 'ethan.rodriguez@example.com',
    phoneNumber: '+66 345 901 678',
    latitude: 13.7552,
    longitude: 100.5063,
  },
  {
    providerId: 'P99001BKK',
    firstName: 'Chloe',
    lastName: 'Walker',
    email: 'chloe.walker@example.com',
    phoneNumber: '+66 456 012 789',
    latitude: 13.7578,
    longitude: 100.509,
  },
  {
    providerId: 'P10223BKK',
    firstName: 'Alexander',
    lastName: 'Hernandez',
    email: 'alexander.hernandez@example.com',
    phoneNumber: '+66 567 123 890',
    latitude: 13.7583,
    longitude: 100.51,
  },
  {
    providerId: 'P21334BKK',
    firstName: 'Ava',
    lastName: 'Allen',
    email: 'ava.allen@example.com',
    phoneNumber: '+66 678 234 901',
    latitude: 13.752,
    longitude: 100.5116,
  },
  {
    providerId: 'P32445BKK',
    firstName: 'Jackson',
    lastName: 'Young',
    email: 'jackson.young@example.com',
    phoneNumber: '+66 789 345 012',
    latitude: 13.7538,
    longitude: 100.502,
  },
  {
    providerId: 'P43556BKK',
    firstName: 'Amelia',
    lastName: 'King',
    email: 'amelia.king@example.com',
    phoneNumber: '+66 890 456 123',
    latitude: 13.7548,
    longitude: 100.513,
  },
  {
    providerId: 'P54667BKK',
    firstName: 'Samuel',
    lastName: 'Wright',
    email: 'samuel.wright@example.com',
    phoneNumber: '+66 901 567 234',
    latitude: 13.7574,
    longitude: 100.5143,
  },
  {
    providerId: 'P65778BKK',
    firstName: 'Grace',
    lastName: 'Lopez',
    email: 'grace.lopez@example.com',
    phoneNumber: '+66 012 678 345',
    latitude: 13.7501,
    longitude: 100.5099,
  },
  {
    providerId: 'P76889BKK',
    firstName: 'Lucas',
    lastName: 'Gonzalez',
    email: 'lucas.gonzalez@example.com',
    phoneNumber: '+66 123 890 123',
    latitude: 13.7556,
    longitude: 100.5079,
  },
  {
    providerId: 'P87990BKK',
    firstName: 'Zoe',
    lastName: 'Nelson',
    email: 'zoe.nelson@example.com',
    phoneNumber: '+66 234 901 234',
    latitude: 13.7568,
    longitude: 100.5102,
  },
  {
    providerId: 'P98001BKK',
    firstName: 'Isaac',
    lastName: 'Harris',
    email: 'isaac.harris@example.com',
    phoneNumber: '+66 345 012 345',
    latitude: 13.7533,
    longitude: 100.5107,
  },
  {
    providerId: 'P10234BKK',
    firstName: 'Lily',
    lastName: 'Martin',
    email: 'lily.martin@example.com',
    phoneNumber: '+66 456 123 456',
    latitude: 13.757,
    longitude: 100.5125,
  },
  {
    providerId: 'P21345BKK',
    firstName: 'Mason',
    lastName: 'Lee',
    email: 'mason.lee@example.com',
    phoneNumber: '+66 567 234 567',
    latitude: 13.7541,
    longitude: 100.5119,
  },
  {
    providerId: 'P32456BKK',
    firstName: 'Charlotte',
    lastName: 'Perez',
    email: 'charlotte.perez@example.com',
    phoneNumber: '+66 678 345 678',
    latitude: 13.7592,
    longitude: 100.5137,
  },
  {
    providerId: 'P43567BKK',
    firstName: 'Leo',
    lastName: 'Scott',
    email: 'leo.scott@example.com',
    phoneNumber: '+66 789 456 789',
    latitude: 13.7534,
    longitude: 100.5104,
  },
  {
    providerId: 'P54678BKK',
    firstName: 'Victoria',
    lastName: 'Green',
    email: 'victoria.green@example.com',
    phoneNumber: '+66 890 567 890',
    latitude: 13.7553,
    longitude: 100.5081,
  },
];

const serviceData = [
  {
    providerId: 'P12345BKK',
    subCatId: 11,
  },
  {
    providerId: 'P12345BKK',
    subCatId: 57,
  },
  {
    providerId: 'P54321BKK',
    subCatId: 72,
  },
  {
    providerId: 'P23456BKK',
    subCatId: 61,
  },
  {
    providerId: 'P87654BKK',
    subCatId: 31,
  },
  {
    providerId: 'P87654BKK',
    subCatId: 11,
  },
  {
    providerId: 'P65432BKK',
    subCatId: 24,
  },
];

async function seedDatabase() {
  // prisma command here

  await prisma.user.createMany({
    data: userData,
  });

  await prisma.provider.createMany({
    data: providerData,
  });

  await prisma.category.createMany({
    data: categoryData,
  });

  await prisma.service.createMany({
    data: serviceData,
  });
}

console.log('Seeding Database...');
seedDatabase();
